print("Hello, Debbie")
print("Hello, Debbie This is your first code")
print("Hello, Monday It's a new beginning")
print("Hello, Tuesday")
print("Hello, Wednesday, working on API Testing")
print("Hello, Thursday. I will be Reporting my Project on Testrail")