print("Hello, Debbie")
print("Hello, Debbie This is your first code")
print("Hello, Monday It's a new beginning")
print("Hello, Tuesday")
print("Hello, Wednesday, working on API Testing")
print("Hello, Thursday. I will be Reporting my Project on Testrail")
print("Hello, Friday it's a coding weekend")
print("Hello, Saturday ")
print("Hello, Saturday Code pull from git to command")
print("This weekend I'm learning Javascripts")
print("Code and python learning make easy with ConfixHub")
